# Generated by Django 5.2.4 on 2025-07-24 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_productinfo_external_id_alter_productinfo_model_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productinfo',
            name='external_id',
            field=models.PositiveIntegerField(),
        ),
    ]
