# Generated by Django 5.2.4 on 2025-07-31 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_alter_category_name_alter_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='accepting_orders',
            field=models.BooleanField(default=True),
        ),
    ]
